server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
spring:
  application:
    name: graph-domain-backend
  threads:
    virtual:
      enabled: true
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_picture?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  servlet:
    multipart:
      max-file-size: 10MB
  # 邮件配置
  mail:
    username: ${MAIL_FROM:fgx156@126.com} # 发件人邮箱
    password: ${MAIL_PASSWORD:BRrgWMeNrAUwMH6x}  # 邮箱授权码
    host: ${MAIL_HOST:smtp.126.com} # SMTP服务器地址
    port: ${MAIL_PORT:465} # SMTP服务器端口
    admin: ${ADMIN_MAIL:402130564@qq.com} # 管理员邮箱
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  # Redis配置
  redis:
    port: ${REDIS_PORT:6379}
    host: localhost
    database: 1
  # ES 配置
  elasticsearch:
    connection-timeout: 50000
    uris: ${ES_URIS:http://localhost:9200}
    socket-timeout: 60000
    username: ${ES_USERNAME:}  # 可选，没配置就是空
    password: ${ES_PASSWORD:}  # 可选，没配置就是空

  ai:
    dashscope:
      api-key: sk-f1deb803cef74837b3a2f8a5dc129d6f
      image:
        options:
          model: qwen-image-plus      # 默认走"生成"模型

# mybatis-plus配置
mybatis-plus:
  configuration:
    # MyBatis 配置,将下划线转为驼峰
    map-underscore-to-camel-case: false
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除
      logic-delete-field: deleted
      logic-delete-value: 1 # 逻辑删除 默认为1
      logic-not-delete-value: 0 # 逻辑未删除 默认为0

# 腾讯云 对象存储配置
cos:
  client:
    enable: true
    duration: 1800
    host: ${COS_HOST:https://tuyu-1314757004.cos.ap-beijing.myqcloud.com}  # 存储桶访问域名
    secretId: ${COS_SECRET_ID:AKIDeIrFVbWFmAZq7DC1e7PbdYKzUnvsgJEz}  # 腾讯云 SecretId
    secretKey: ${COS_SECRET_KEY:c3IQN7e3IXcYMzRtAIF2e6QaZDiy63rT}  # 腾讯云 SecretKey
    region: ${COS_REGION:ap-beijing}  # 存储桶所在地域
    bucket: ${COS_BUCKET:tuyu-1314757004}  # 存储桶名称

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan:
        - com.xin.graphdomainbackend

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn