spring:
  profiles:
    active: dev

# 以下内容是application-dev.yml, 含有your_需要配置成自己的账号和密码
#server:
#  port: 8080
#  servlet:
#    context-path: /api
#spring:
#  application:
#    name: graph-domain-backend
#  # 数据库配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/yu_picture?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
#    username: your_account
#    password: your_password
#  servlet:
#    multipart:
#      max-file-size: 10MB
#  # 邮件配置
#  mail:
#    username: ${MAIL_FROM:your_email} # 发件人邮箱
#    password: ${MAIL_PASSWORD:your_code}  # 邮箱授权码
#    host: ${MAIL_HOST:smtp.126.com} # SMTP服务器地址,以126邮箱为例
#    port: ${MAIL_PORT:465} # SMTP服务器端口
#    admin: ${ADMIN_MAIL:your_email} # 管理员邮箱
#    properties:
#      mail:
#        smtp:
#          ssl:
#            enable: true
#  # Redis配置
#  redis:
#    port: 6379
#    host: localhost
#    database: 1
#  # ES 配置
#  elasticsearch:
#    connection-timeout: 50000
#    uris: ${ES_URIS:http://localhost:9200}
#    socket-timeout: 60000
#    username:  # 可选，没配置就是空
#    password:  # 可选，没配置就是空
#
#  ai:
#    dashscope:
#      api-key: your_apiKey
#      image:
#        options:
#          model: qwen-image-plus      # 默认走"生成"模型
#
## mybatis-plus配置
#mybatis-plus:
#  configuration:
#    # MyBatis 配置,将下划线转为驼峰
#    map-underscore-to-camel-case: false
#    # 仅在开发环境打印日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      # 逻辑删除
#      logic-delete-field: deleted
#      logic-delete-value: 1 # 逻辑删除 默认为1
#      logic-not-delete-value: 0 # 逻辑未删除 默认为0
#
## 腾讯云 对象存储配置
#cos:
#  client:
#    enable: true
#    duration: 1800
#    host: ${COS_HOST:your_url}  # 存储桶访问域名
#    secretId: ${COS_SECRET_ID:your_id}  # 腾讯云 SecretId
#    secretKey: ${COS_SECRET_KEY:your_key}  # 腾讯云 SecretKey
#    region: ${COS_REGION:ap-beijing}  # 存储桶所在地域
#    bucket: ${COS_BUCKET:your_bucket_name}  # 存储桶名称
#

## Cloudflare 配置
#cloudflare:
#  ai:
#    api-token: ${CLOUDFLARE_API_TOKEN:your_token}
#    account-id: ${CLOUDFLARE_ACCOUNT_ID:your_id}
#    model: "@cf/stabilityai/stable-diffusion-xl-base-1.0"   # 模型名称

## 接口文档配置
#knife4j:
#  enable: true
#  openapi:
#    title: "接口文档"
#    version: 1.0
#    group:
#      default:
#        api-rule: package
#        api-rule-resources:
#          - com.xin.graphdomainbackend
